Repository AY2122S1-CS2103T-T10-1/tp, pull requests merged in 2021-11, with the labels that each got.

#218 Update regex in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low, severity.Low, mustfix

#217 Separate `edit profile` feature from `edit` feature in User Guide.
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium, severity.Low, mustfix

#219 Update ProfileSetUpWindow Title
  src/main/resources/view/ProfileSetUpWindow.fxml
Labels: priority.Medium, type.Enhancement, mustfix

#220 Fix Tab Pane Null
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Task, priority.High

#221 Find feature bug fix
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: priority.High, mustfix

#223 Fix Event Tab
  src/main/java/seedu/address/model/person/IsEventTagPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPaneHeader.java
Labels: priority.High

#222 Update Help Section in App
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/TableView.css
Labels: priority.High, type.Enhancement, mustfix

#225 Fix Bug
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.Medium

#226 Update Command Error Messages and UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Documentation, priority.High, type.Enhancement, mustfix

#227 Update Favourite and Unfavourite Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High, type.Enhancement, mustfix

#228 Update Add Command error messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium, mustfix

#230 Add acknowledgements and update formatting
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, type.Documentation

#224 More v1.4 Bug Fixes
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/person/Github.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#232 Increase Test Coverage
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
Labels: type.Bug, priority.High, mustfix

#238 Update find by tag to be case insensitive
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, mustfix

#237 Update find section of UG
  docs/UserGuide.md
Labels: type.Documentation, mustfix

#240 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Documentation, type.Bug, priority.High, mustfix

#241 Update Format
  docs/UserGuide.md
Labels: type.Documentation, priority.High, mustfix

#242 Add tag command
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#243 Update Format
  docs/UserGuide.md
Labels: type.Documentation, priority.High, mustfix

#245 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Documentation, priority.High, mustfix

#249 Clarify import command
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#250 Add Test Cases for AI and LangColorUtil
  src/test/java/seedu/address/commons/util/LangColorUtilTest.java
  src/test/java/seedu/address/logic/ai/AiTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#252 Update definition of favourite and unfavourite features in User Guide
  docs/UserGuide.md
Labels: type.Documentation, severity.Low

#253 Add Show Command Test Cases
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
Labels: priority.High

#254 Add More Test Cases
  src/test/java/seedu/address/model/person/FindABuddyPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High

#256 Tag command bug fix
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
Labels: priority.High

#258 Increase Test Coverage
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/data/ExportImportCommandTest/TestFiles/duplicatePerson.json
  src/test/data/ExportImportCommandTest/TestFiles/wronglyFormatted.csv
  src/test/data/ExportImportCommandTest/TestFiles/wronglyFormatted.json
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableUserProfileTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, mustfix

#259 Add test cases for Favourite and Unfavourite Command
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, goodtofix

#261 Add specific output for `TagCommand`.
  src/main/java/seedu/address/logic/commands/TagCommand.java
Labels: severity.Low, goodtofix

#257 Add Test Cases
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
Labels: priority.Medium, goodtofix

#262 Increase test coverage
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.High, goodtofix

#264 Added test classes for Tag Command
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, mustfix

#265 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#266 Update User Guide
  docs/UserGuide.md
  docs/images/UiLabelled.png
Labels: type.Documentation, priority.Medium

#268 Update Tag command section of UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#263 Add Test Cases
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/commons/util/GitHubUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/GithubTest.java
  src/test/java/seedu/address/model/person/IsEventTagPredicateTest.java
  src/test/java/seedu/address/model/person/IsFavouritePredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
Labels: priority.Medium, goodtofix

#269 PPP Draft
  docs/team/jai2501.md
Labels: type.Documentation

#270 Update UserGuide.md
  docs/UserGuide.md
  docs/images/HelpWindowUi.png
Labels: type.Documentation, mustfix

#271 Update HelpWindow CommandDetails
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/WelcomeWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, type.Enhancement, mustfix

#272 Add More Test Cases
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/GithubContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/IsFavouritePredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TelegramHandleContainsKeywordsPredicateTest.java
Labels: priority.High, mustfix

#274 Increase test coverage for EditCommand
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High

#277 Fix GUI bug for `UnfavouriteCommand`.
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
Labels: type.Bug, priority.High, severity.Low, mustfix

#273 Increase Test Coverage
  invalidUserProfile.json
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/commons/core/MessagesTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/JsonUserProfileStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  userprofile.json
  userprofilesave.json
Labels: priority.Medium, goodtofix

#275 Update Developer Guide and PPP
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ExportSequenceDiagramStep1.puml
  docs/diagrams/ExportSequenceDiagramStep2.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
  docs/images/ExportSequenceDiagramStep1.png
  docs/images/ExportSequenceDiagramStep2.png
  docs/images/ImportSequenceDiagram.png
  docs/team/moretriangles.md
Labels: type.Documentation, priority.High

#281 Edit profile bug fix
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/storage/JsonUserProfileStorage.java
  src/test/data/JsonUserProfileStorageTest/userprofile.json
  src/test/data/JsonUserProfileStorageTest/userprofilesave.json
  src/test/data/StorageManagerTest/userprofile.json
  src/test/data/StorageManagerTest/userprofilesave.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonUserProfileStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High

#282 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/HelpWindowSequenceDiagram.puml
  docs/diagrams/ProfileSetUpWindowSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UserProfileInMenuBarSequenceDiagram.puml
  docs/diagrams/UserProfileWindowSequenceDiagram.puml
  docs/diagrams/WelcomeWindowSequenceDiagram.puml
  docs/images/HelpWindowSequenceDiagram.png
  docs/images/ProfileSetUpWindowSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UserProfileInMenuBarSequenceDiagram.png
  docs/images/UserProfileWindowSequenceDiagram.png
  docs/images/WelcomeWindowSequenceDiagram.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UserProfileInMenuBar.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#294 Minor bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Telegram.java
Labels: priority.High, mustfix

#283 Update edit profile section of UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#296 Fix edit command error messages.
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, priority.High, mustfix

#297 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/ProfileSetUpWindowInvalidCredentialsSequenceDiagram.puml
  docs/diagrams/ProfileSetUpWindowTypicalScenarioSequenceDiagram.puml
  docs/diagrams/UserProfileInMenuBarSequenceDiagram.puml
  docs/images/HelpWindowVisitURLButton.png
  docs/images/ProfileSetUpWindowInvalidCredentialsSequenceDiagram.png
  docs/images/ProfileSetUpWindowTypicalScenarioSequenceDiagram.png
  docs/images/UserProfileInMenuBarPictureHighlight.png
  docs/images/UserProfileInMenuBarSequenceDiagram.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Documentation, priority.High

#300 Update Commands in HelpWindow and UserGuide.md
  docs/UserGuide.md
  docs/images/HelpWindowUi.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Documentation, priority.High, type.Enhancement

#304 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/EditProfileSequenceDiagram.puml
  docs/diagrams/FindGithubSequenceDiagram.puml
  docs/diagrams/FindNameSequenceDiagram.puml
  docs/diagrams/FindTagsSequenceDiagram.puml
  docs/diagrams/TagSequenceDiagramForAdd.puml
  docs/diagrams/TagSequenceDiagramForAddAndRemove.puml
  docs/images/EditProfileSequenceDiagram.png
  docs/images/FindGithubSequenceDiagram.png
  docs/images/FindNameSequenceDiagram.png
  docs/images/FindTagsSequenceDiagram.png
  docs/images/TagSequenceDiagramForAdd.png
  docs/images/TagSequenceDiagramForAddAndRemove.png
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
Labels: type.Documentation, priority.High

#303 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  src/main/resources/view/WelcomeWindow.css
  src/main/resources/view/WelcomeWindow.fxml
Labels: type.Documentation, priority.High

#302 Update requirements, and use cases
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#309 Add PPP
  docs/team/aishh12.md
Labels: type.Task, priority.High

#311 Add formatting changes to PPP
  docs/team/aishh12.md
Labels: type.Task, priority.High

#312 Edit PPP
  docs/team/aishh12.md
Labels: type.Task, priority.High

#307 Update Product Website
  docs/AboutUs.md
  docs/index.md
Labels: type.Documentation

#310 Fix Use Case End Not Shown Issue
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#313 Edit PPP
  docs/team/aishh12.md
Labels: type.Task, priority.High

#314 Update Portfolio Page
  docs/team/moretriangles.md
Labels: type.Documentation, priority.High

#315 Update formatting for PPP
  docs/team/moretriangles.md
Labels: type.Documentation

#316 Update Storage and Export diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagramStep1.puml
  docs/diagrams/ExportSequenceDiagramStep2.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ExportSequenceDiagramStep1.png
  docs/images/ExportSequenceDiagramStep2.png
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#318 Add minor edits to UG
  docs/UserGuide.md
Labels: priority.High

#319 Update dg use cases
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#323 Add PPP
  docs/team/cheongyeeming.md
Labels: type.Documentation, priority.High

#324 Update PPP
  docs/team/cheongyeeming.md
Labels: priority.High, mustfix

#321 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/FavoriteSequenceDiagram.puml
  docs/diagrams/PersonOptionalFieldClassDiagram.puml
  docs/diagrams/PersonWithGithubClassDiagram.puml
  docs/diagrams/UnfavoriteSequenceDiagram.puml
  docs/images/FavoriteSequenceDiagram.png
  docs/images/PersonOptionalFieldClassDiagram.png
  docs/images/PersonWithGithubClassDiagram.png
  docs/images/UnfavoriteSequenceDiagram.png
Labels: type.Documentation, priority.High

#322 Update Javadocs, comments, and refactoring
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/test/java/seedu/address/logic/commands/GithubCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/TelegramCommandTest.java
  src/test/java/seedu/address/storage/CsvAdaptedPersonTest.java
  src/test/java/seedu/address/storage/CsvAddressBookStorageTest.java
Labels: type.Documentation

#325 Update PPP
  docs/team/cheongyeeming.md
Labels: priority.High, mustfix

#328 Update PPP
  docs/team/cheongyeeming.md
Labels: priority.High, mustfix

#329 Fix formatting issue in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, type.Bug

#332 Fix ordered list
  docs/DeveloperGuide.md
Labels: type.Documentation, type.Bug

#330 Update HelpWindow Edit Command
  docs/images/HelpWindowUi.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Documentation, priority.High

#336 Minor Refactor and Bug Fix
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
Labels: priority.Medium

#338 Update UiClassDiagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiOtherComponentsDiagram.puml
  docs/diagrams/UiWindowsDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiOtherComponentsDiagram.png
  docs/images/UiWindowsDiagram.png
Labels: type.Documentation, priority.High

#339 Minor Tweak
  docs/team/jai2501.md
Labels: type.Documentation

#340 Fix inconsistency in tips and notes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#341 Add Page Break - PPP
  docs/team/jai2501.md
Labels: type.Documentation

#342 Fix long code block in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#343 PPP - Quick Link Update
  docs/team/jai2501.md
Labels: type.Documentation

#345 Fix info about manual testing
  docs/DeveloperGuide.md
Labels: type.Documentation

#346 Update test case and move test case file
  src/test/data/StorageManagerTest/invalidUserProfile.json
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium

#348 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High
