Repository AY2122S1-CS2103T-T10-1/tp, pull requests merged in 2021-10, with the labels that each got.

#39 Implement export to json
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: type.Task

#41 Add find by tags feature
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
Labels: type.Task

#46 Fix format for ExportCommand invalid format
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Bug

#54 Add Telegram field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/view/PersonDetails.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High, type.Enhancement

#56 Add optional fields
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Task, priority.High

#58 Add unit testing for ExportCommand
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/data/ExportCommandTest/FileExists/testFile.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Task, priority.High

#69 Update and Fix User Guide Bug
  docs/UserGuide.md
Labels: type.Documentation, type.Bug, severity.High

#72 Update UserGuide.md to include find by telegram handle(s) feature
  docs/UserGuide.md
Labels: type.Documentation

#86 Add clickable telegram handle
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/view/PersonDetails.fxml
Labels: type.Task, priority.High

#87 Implement up and down arrows keys to access previous commands
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandHistory.java
Labels: type.Task, priority.Medium

#99 Update Developer Guide with implementation of Export
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Task, type.Documentation

#101 Developer guide - make return arrows dotted
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
Labels: type.Documentation

#102 Add logging for Command History
  src/main/java/seedu/address/ui/CommandHistory.java
Labels: type.Task

#111 Enable Assertions
  build.gradle
Labels: priority.High

#113 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/PersonOptionalFieldClassDiagram.puml
  docs/diagrams/PersonWithGithubClassDiagram.puml
  docs/diagrams/PersonWithTelegramClassDiagram.puml
  docs/images/PersonOptionalFieldClassDiagram.png
  docs/images/PersonWithGithubClassDiagram.png
  docs/images/PersonWithTelegramClassDiagram.png
Labels: type.Documentation, priority.High

#184 Make Comments consistent
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/GitHubUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/logic/parser/UnfavouriteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/CsvSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/JsonUserProfileStorage.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/storage/UserProfileStorage.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/WelcomeWindow.java
Labels: type.Documentation, priority.Medium

#197 Fix GUI Bug: Name Not Update in Menu Bar
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/util/UserProfileWatcher.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileSetUpWindow.java
  src/main/java/seedu/address/ui/UserProfileInMenuBar.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UserProfileInMenuBar.fxml
Labels: type.Bug, severity.Medium, type.Enhancement

#209 Update telegram regex.
  src/main/java/seedu/address/model/person/Telegram.java
Labels: priority.High, severity.High

#214 Bug Fixes
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileSetUpWindow.java
Labels: type.Bug, priority.High, severity.Medium
